# color schemes
schemes:
    base_16: &dark
        # Colors (Base16 Default Dark)
        colors:
          # Default colors
          primary:
            background: '#181818'
            foreground: '#d8d8d8'

          # Colors the cursor will use if `custom_cursor_colors` is true
          cursor:
            text: '#d8d8d8'
            cursor: '#d8d8d8'

          # Normal colors
          normal:
            black:   '#181818'
            red:     '#ab4642'
            green:   '#a1b56c'
            yellow:  '#f7ca88'
            blue:    '#7cafc2'
            magenta: '#ba8baf'
            cyan:    '#86c1b9'
            white:   '#d8d8d8'

          # Bright colors
          bright:
            black:   '#585858'
            rd:     '#ab4642'
            green:   '#a1b56c'
            yellow:  '#f7ca88'
            blue:    '#7cafc2'
            magenta: '#ba8baf'
            cyan:    '#86c1b9'
            white:   '#f8f8f8'

# font config
font:
  size: 9 
  normal:
    family: Fira Code
    style: Regular

  bold:
    family: Fira Code 
    style: Bold

  italic:
    family: Fira Code 
    style: Italic

  bold_italic:
    family: Fira Code 
    style: Bold Italic
