[theme]
theme = "gruvbox-dark"
[icons]
icons = "awesome"

[[block]]
block = "github"
interval = 1800 # check every half hour (in seconds)

[[block]]
block="pacman"
interval = 600
format = " $pacman + $aur = $both updates available "
format_singular = " $both update available "
format_up_to_date = " $icon up-to-date "
critical_updates_regex = "(linux|linux-lts|linux-zen)"
aur_command = "yay -Qua"

[[block]]
block = "memory"
format = " $icon $mem_total_used_percents "

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "sound"

[[block]]
block="backlight"
device="intel_backlight"
step_width = 15 #set in .config/i3/config

[[block]]
block = "battery"
device="BAT1"
driver = "upower"
interval=10
full_threshold = 99
format = " $icon $percentage "

[[block]]
block = "time"
interval = 60
# format = " %a %d/%m %R "

