theme = "gruvbox-dark"
icons = "awesome"

# [[block]]
# block = "music"
# player = "spotify"
# buttons = ["prev","play", "next"]
# on_collapsed_click = "spotify"

# [[block]]
# block = "disk_space"
# path = "/"
# alias = "/"
# info_type = "available"
# unit = "GB"
# interval = 20
# warning = 20.0
# alert = 10.0

[[block]]
block = "focused_window"
max_width=50
show_marks="visible"

[[block]]
block="pacman"
interval = 600
format = "{pacman} updates available"
format_singular = "{pacman} update available"
format_up_to_date = "up-to-date"
critical_updates_regex = "(linux|linux-lts|linux-zen)"
on_click = "fakeroot pacman -Qu -dbpath /tmp/checkup-db-hasan/ | wofi --show dmenu"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
clickable = true

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "sound"

[[block]]
block="backlight"
device="intel_backlight"
step_width = 15 #set in .config/i3/config


# [[block]]
# block = "xrandr"
# icons = true
# resolution = true
# interval = 2

[[block]]
block = "battery"
device="BAT1"
driver = "upower"
interval=10
format = "{percentage} {time}"

# [[block]]
# block = "networkmanager"
# ap_format =  "{ssid}"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"

